export const CONTENT_STATUSES = ['draft', 'approved', 'archived', 'cancelled'] as const;

export type ContentStatus = (typeof CONTENT_STATUSES)[number];

export const CONTENT_TYPES = ['video', 'text'] as const;

export type ContentType = (typeof CONTENT_TYPES)[number];

/**
 * Persisted content. Platform-independent: no Facebook/TikTok/Shopee fields.
 * Structured affiliate copy (hook, script, caption, CTA, hashtags) is generated by AI
 * and packed into `title` / `body` for persistence until a dedicated schema is needed.
 */
export interface Content {
  id: string;
  userId: string;
  title: string;
  body: string;
  status: ContentStatus;
  contentType: ContentType;
  metadata: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

/** Well-known metadata keys for affiliate-generated content. */
export interface AffiliateContentMetadata {
  productId: string;
  affiliateOfferId: string;
  affiliateUrl: string;
}

export function parseAffiliateContentMetadata(
  metadata: Record<string, unknown>,
): AffiliateContentMetadata | null {
  const productId = metadata.productId;
  const affiliateOfferId = metadata.affiliateOfferId;
  const affiliateUrl = metadata.affiliateUrl;
  if (
    typeof productId === 'string' &&
    typeof affiliateOfferId === 'string' &&
    typeof affiliateUrl === 'string' &&
    affiliateUrl.trim().length > 0
  ) {
    return { productId, affiliateOfferId, affiliateUrl };
  }
  return null;
}

/**
 * Channel-neutral affiliate copy. Not a D1 schema — do not persist as extra columns yet.
 */
export interface AffiliateContentCopy {
  hook: string;
  script: string;
  caption: string;
  cta: string;
  hashtags: string[];
  language?: string;
  tone?: string;
}

export const CONTENT_TRANSITIONS: Record<ContentStatus, ContentStatus[]> = {
  draft: ['approved', 'cancelled'],
  approved: ['archived', 'cancelled', 'draft'],
  archived: [],
  cancelled: [],
};

export function canTransitionContentStatus(from: ContentStatus, to: ContentStatus): boolean {
  return CONTENT_TRANSITIONS[from].includes(to);
}

export function mapAffiliateDraftToContentFields(input: {
  hook: string;
  script: string;
  caption: string;
  cta: string;
  hashtags: string[];
  videoScenePlan?: string;
}): { title: string; body: string } {
  const title = input.hook.trim();
  const body = [
    input.script,
    input.caption,
    input.cta,
    input.hashtags.join(' ').trim(),
    input.videoScenePlan,
  ]
    .filter((part) => Boolean(part?.trim()))
    .join('\n\n');

  return { title, body };
}
