export interface Env {
  DB: D1Database;
  MEDIA_BUCKET: R2Bucket;
  PUBLISH_QUEUE: Queue<{ scheduledPostId: string }>;
  AI: Ai;
  ENVIRONMENT: string;
  AI_PROVIDER: string;
  OPENAI_API_KEY?: string;
  CORS_ORIGIN?: string;
  SHOPEE_AFFILIATE_APP_ID?: string;
  SHOPEE_AFFILIATE_SECRET?: string;
  SHOPEE_AFFILIATE_ENDPOINT?: string;
  TOKEN_WRAP_KEY?: string;
  FACEBOOK_GRAPH_API_VERSION?: string;
  USE_MOCK_FACEBOOK_PUBLISHER?: string;
  AFFILIATE_PIPELINE_CRON?: string;
  AFFILIATE_PIPELINE_ENABLED?: string;
  AFFILIATE_PIPELINE_INTERVAL_HOURS?: string;
  AFFILIATE_PIPELINE_LIMIT?: string;
  AFFILIATE_PIPELINE_KEYWORD?: string;
  AFFILIATE_PIPELINE_DUPLICATE_WINDOW_HOURS?: string;
  AFFILIATE_PIPELINE_GENERATE_MEDIA?: string;
  AFFILIATE_PIPELINE_TONE?: string;
  AFFILIATE_PIPELINE_LANGUAGE?: string;
}
